name: 'testaction'
description: 'test action'
inputs:
  image:
    description: "docker image name"
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v1
    - id: branch_names
      uses: ./github/actions/shelltestaction/
    - uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - id: source_caches
      shell: bash
      run: |
        export PYTHONPATH=${{ github.action_path }}/..
        python3 -m studiodockercaches ${{ steps.branch_names.output.parent_branch_name }} ${{ steps.branch_names.output.current }} ${{ inputs.parent_branch_name }}