name: simulation
on:
  push:
    branches:
      - 'main'
  workflow_dispatch:
jobs:
  navigation_tests:
    runs-on: ubuntu-22.04
    container:
      image: ros:galactic
    steps:
      - name: mount configuration directory
        run: |
          ls -al
          pwd
          mkdir -p config
          touch config/thefile.txt
          ls -al config/
          sudo mkdir -p /etc/opt/birdseye
          ls -al /etc
          ls -al /etc/opt
          ls -al /etc/opt/birdseye
          sudo mount --bind ${{ github.workspace }}/config /etc/opt/birdseye
