name: simulation
on:
  push:
    branches:
      - 'main'
  workflow_dispatch:
jobs:
  navigation_tests:
    runs-on: ubuntu-22.04
    container:
      image: ros:galactic
      options: --security-opt apparmor:unconfined --cap-add=SYS_ADMIN
    steps:
      - name: mount configuration directory
        run: |
          mkdir -p config
          touch config/thefile.txt
          sudo mkdir -p /etc/opt/birdseye
          sudo mount --bind ./config /etc/opt/birdseye
