# Modified from: https://github.com/ros-planning/navigation2/blob/main/.github/workflows/update_ci_image.yaml

name: Build and Test

on:
  # # Run workflow on-demand
  workflow_dispatch:
  # Run workflow on-push to main or release branches
  push:
    branches:
      - main
      - v[0-9]+\.[0-9]+
  # Run workflow on-PR to any branch
  pull_request:

jobs:
  build_image:
    name: Build underlay image
    runs-on:  ubuntu-22.04
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build Dockerfile underlay stage and push to GHCR
        uses: docker/build-push-action@v3
        with:
          context: .
          target: pre-overlay  # NOTE: This is actually the underlay plus the rosdeps for the overlay
          push: true
          tags: ghcr.io/orensbruli/ci_playground
          # Cache from main, the base ref (if the context is a Pull Request), and this branch's previous builds
          # TODO: Remove the old build cache-from sources (those without -buildcache) once most PRs have been rebased and have their cache sources updated
          cache-from: |
            type=registry,ref=ghcr.io/orensbruli/ci_playground:buildcache
            type=registry,ref=ghcr.io/orensbruli/ci_playground
            type=registry,ref=alpine:latest
            
          cache-to: type=registry,ref=ghcr.io/orensbruli/ci_playground:buildcache,mode=max

