name: CD

on:
  # Run workflow on pushes (including tags) on main branch
  push:
    branches:
      - main
  
  # Run workflow on tag creation with the specific pattern
  create:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+-rc[0-9]+'
  
  # Run workflow on release creation
  release:
    types:
      - created

jobs:
  deploy_dev:
    name: Deploy to Dev
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment:
      name: Development
      url: 'ssh://<user>@<dev-host>:<port>'
    steps:
      - name: Deploy
        run: |
           echo "$SSHKEY" > ~/.ssh/development.key 
           ssh -i ~/.ssh/development.key ${SSHUSER}@${SSHHOST} "ls; pwd; df"

  deploy_staging:
    name: Deploy to Staging
    if: github.event_name == 'create' && startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    environment:
      name: Staging
      url: 'ssh://<user>@<staging-host>:<port>'
    steps:
      - name: Deploy
        run: echo "I am deploying to staging!"

  deploy_prod:
    name: Deploy to Production
    if: github.event_name == 'release' && github.event.action == 'created'
    runs-on: ubuntu-latest
    environment:
      name: Production
      url: 'ssh://<user>@<prod-host>:<port>'
    steps:
      - name: Deploy
        run: echo "I am deploying to prod!"
