# a workflow depending on other


name: Test in chain

on:
  workflow_run:
    workflows: [ Test in chain ]
    types:
      - completed

jobs:
    test:
      runs-on: ubuntu-latest
      steps:
        - run: echo "Release the Docker image..."