name: custom action

on:
  # # Run workflow on-demand
  workflow_dispatch:

jobs:
  release:
    name: Test custom action
    runs-on:  ubuntu-22.04
    steps:
      - uses: actions/checkout@v1
      - uses: ./.github/actions/pythontestaction
      - id: shell_action
        uses: ./.github/actions/shelltestaction
        with:
          argvs: 'patata'
      - run: echo ${{ steps.shell_action.outputs.random-number }}
        