name: custom action

on:
  # # Run workflow on-demand
  workflow_dispatch:

jobs:
  release:
    name: Test custom action
    runs-on:  ubuntu-22.04
    steps:
      - uses: actions/checkout@v1
      - uses: ./.github/actions/pythontestaction
      - uses: ./.github/actions/shelltestaction