name: docker metadata

on:
    workflow_dispatch:
    pull_request:
    push:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            name/app
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha
            type=raw,patata
      - name: output
        run: |
            echo "${{ steps.meta.outputs.tags }}"