name: buildx_fail
on:
  workflow_dispatch:
  push:
  pull_request:

permissions:
  packages: write


jobs:
  builddocker:
    name: builddocker
    runs-on: ubuntu-latest
   
    steps:
      - name: Dump GitHub context for understanding/debugging
        id: github_context_step
        run: echo $JSON
        env:
          JSON: ${{ toJSON(github) }}
      # Checkout PR HEAD instead of PR MERGE_HEAD to prevent clobbering already-named Docker tags on the remote
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2.0.0
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: manually docker build
        run: /usr/bin/docker buildx build --provenance false --cache-to type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/patata:onething,mode=max .
