name: detect closed pr


jobs:
  on_pr:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "value of github.event.pull_request.merged is  ${{ github.event.pull_request.merged }}"
    - name: Instalar jq
      run: sudo apt-get install jq

    - name: Imprimir información del evento
      run: cat $GITHUB_EVENT_PATH | jq .
    
  job-cuando-pr-cerrado:
    runs-on: ubuntu-latest
    if: github.event.pull_request.closed_at != null
    steps:
    - name: Ejecutar si el PR está cerrado
      run: echo "Este PR está cerrado."

  job-cuando-pr-abierto:
    runs-on: ubuntu-latest
    if: github.event.pull_request.closed_at == null
    steps:
    - name: Ejecutar si el PR está abierto
      run: echo "Este PR aún está abierto."