# Reusable workflow for building Docker images
on:
  workflow_call:
    # List of names of other workflows that must complete successfully before this workflow can run
    needs:
      required: true
      type: string


jobs:
  job_name:
    name: Any job name
    needs: fromJson(${{ inputs.needs }})
    runs-on:
    steps:
      run: echo "Hello World after ${{ inputs.needs }}"