name: Reusable workflow for building Docker images

on:
  workflow_call:
    inputs:
      patata:
        required: true
        type: string

jobs:
  job_name:
    name: Any job name
    runs-on: ubuntu-latest
    needs: ${{ inputs.patata }}
    steps:
      - name: Hello World
        run: echo "Hello World after ${{ inputs.patata }}"