name: filter by files

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  check_code_changes:
    permissions: write-all
    runs-on: ubuntu-latest
    outputs:
      backend_code: ${{ steps.filter.outputs.backend_code }}
      python_code: ${{ steps.filter.outputs.python_code }}
      frontend_code: ${{ steps.filter.outputs.frontend_code }}
    steps:
      - uses: actions/checkout@v2
        if: github.event_name == 'push'
      - uses: dorny/paths-filter@v2
        id: filter
        with:

          filters: |
            documentation:
              - added|modified: '**/*.md'
              - added|modified: '**/*.rst'
            frontend_code:
              - added|modified: 'src/moveit_studio_web/**'
            python_code:
              - added|modified: '**/*.py'

  job_with_filtered_steps:
    needs:
      - check_code_changes
    runs-on: ubuntu-latest
    steps:
      - name: values of filters
        run: |
          echo "backend_code: ${{ needs.check_code_changes.outputs.backend_code }}"
          echo "python_code: ${{ needs.check_code_changes.outputs.python_code }}"
          echo "frontend_code: ${{ needs.check_code_changes.outputs.frontend_code }}"
      - name: run one thing
        if: needs.check_code_changes.outputs.frontend_code == 'false' && needs.check_code_changes.outputs.documentation == 'false'
        run: echo "run one thing"
      - name: run another thing
        if: !(needs.check_code_changes.outputs.frontend_code == 'true' || needs.check_code_changes.outputs.documentation == 'false')
        run: echo "run another thing"
