name: ternary
on:
  push:
  workflow_dispatch:
jobs:
  navigation_tests:
    runs-on: ubuntu-22.04
    strategy:
        matrix:
          yarn_build: ["build", "build:kiosk"]
    steps:
      - name: mount configuration directory
        run: |
          echo "${{ matrix.yarn_build == 'build:kiosk' && '-kiosk' || '' }}"


